namespace ITI.SkyLord
{
    public enum UnitName
    {
        soldier,
        archer,
        knight,
        griffin,
        champion,
        gobelin,
        harpy,
        dirtGolem,
        troll,
        phenix,
        juggernaut,
        wisp,
        novice,
        necromancer,
        summoner,
        prophet,
        scorpion,
        flameThrower,
        saboteur,
        livingArmor,
        ironGolem,
        prismaticGolem,
        canoe,
        carrier
    }
}